"""
The sirun submodule, not to be used directly atm
"""

from __future__ import annotations

import typing

__all__: list[str] = ["Input", "dbl3", "int3"]

class Input:
    def __init__(self, arg0: dict) -> None: ...
    def add(self, arg0: str, arg1: str) -> None: ...
    def echoKeywords(self) -> None: ...
    def get(self, arg0: str) -> str: ...
    def renameKeys(self, arg0: str, arg1: str) -> None: ...
    def set(self, arg0: str, arg1: str) -> None: ...
    def setDefault(self, arg0: str, arg1: str) -> None: ...

class dbl3:
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> float: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(
        self,
        arg0: typing.SupportsFloat | typing.SupportsIndex,
        arg1: typing.SupportsFloat | typing.SupportsIndex,
        arg2: typing.SupportsFloat | typing.SupportsIndex,
    ) -> None: ...
    @typing.overload
    def __init__(self, arg0: tuple) -> None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(
        self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsFloat | typing.SupportsIndex
    ) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, arg0: typing.SupportsFloat | typing.SupportsIndex) -> None: ...

class int3:
    def __getitem__(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> int: ...
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(
        self,
        arg0: typing.SupportsInt | typing.SupportsIndex,
        arg1: typing.SupportsInt | typing.SupportsIndex,
        arg2: typing.SupportsInt | typing.SupportsIndex,
    ) -> None: ...
    @typing.overload
    def __init__(self, arg0: tuple) -> None: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __setitem__(
        self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex
    ) -> None: ...
    @property
    def x(self) -> int: ...
    @x.setter
    def x(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def y(self) -> int: ...
    @y.setter
    def y(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
    @property
    def z(self) -> int: ...
    @z.setter
    def z(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None: ...
