package:

  name: image3kit
  version: 0.0.2

source:
  path: ..

build:
  number: 0
  script:
    - unset CMAKE_GENERATOR && {{ PYTHON }} -m pip install . -vv  # [not win]
    - {{ PYTHON }} -m pip install . -vv  # [win]

requirements:
  build:
    - python
    - {{ compiler('cxx') }}

  host:
    - openmp  # [win]
    - cmake
    - ninja
    - python
    - pip
    - scikit-build-core
    - pybind11 >=2.10.0

  run:
    - python


test:
  imports:
    - image3kit
  requires:
    - pytest
    - numpy
  source_files:
    - tests
    - pyproject.toml
  commands:
    - pytest tests

about:
  summary: An example project built with pybind11 and scikit-build.
  license_file: LICENSE
